concurrent = 2
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "dsp-be"
  url = "https://gitlab.ifchange.com/"
  token = "gHRza4Hfx6bQx2jmkgDH"
  executor = "shell"
  builds_dir = "/opt/gitlab-runner/builds"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]